	{ "L",				 OPT_EXIT,				NULL,				show_license,		0,      "show license", "" },
    { "h",				 OPT_EXIT,				NULL,				show_help,			0,		"show help", "topic" },
    { "?",				 OPT_EXIT,				NULL,				show_help,			0,      "show help", "topic" },
    { "help",			 OPT_EXIT,				NULL,				show_help,			0,      "show help", "topic" },
    { "-help",			 OPT_EXIT,				NULL,				show_help,			0,      "show help", "topic" },
    { "version",		 OPT_EXIT,				NULL,				show_version,		0,      "show version", "" },
    { "buildconf",		 OPT_EXIT,				NULL,				show_buildconf,		0,		"show build configuration", "" },
    { "formats",		 OPT_EXIT,				NULL,				show_formats,		0,		"show available formats", "" },
    { "devices",		 OPT_EXIT,				NULL,				show_devices,		0,		"show available devices", "" },
    { "codecs",			 OPT_EXIT,				NULL,				show_codecs,		0,		"show available codecs", "" },
    { "decoders",		 OPT_EXIT,				NULL,				show_decoders,		0,		"show available decoders", "" },
    { "encoders",		 OPT_EXIT,				NULL,				show_encoders,		0,		"show available encoders", "" },
	{ "bsfs",			 OPT_EXIT,				NULL,				show_bsfs,			0,		"show available bit stream filters", "" },
    { "protocols",		 OPT_EXIT,				NULL,				show_protocols,		0,		"show available protocols", "" },
    { "filters",		 OPT_EXIT,				NULL,				show_filters,		0,		"show available filters", "" },
    { "pix_fmts",		 OPT_EXIT,				NULL,				show_pix_fmts,		0,		"show available pixel formats", "" },
    { "layouts",		 OPT_EXIT,				NULL,				show_layouts,		0,		"show standard channel layouts", "" },
    { "sample_fmts",	 OPT_EXIT,				NULL,				show_sample_fmts,	0,		"show available audio sample formats", "" },
    { "colors",			 OPT_EXIT,				NULL,				show_colors,		0,		"show available color names", "" },
    { "loglevel",		 HAS_ARG,				NULL,				opt_loglevel,		0,		"set logging level", "loglevel" },
    { "v",				 HAS_ARG,				NULL,				opt_loglevel,		0,		"set logging level", "loglevel" },
    { "report",			 0,						(void*)opt_report,	NULL,				0,		"generate a report", "" },
    { "max_alloc",		 HAS_ARG,				NULL,				opt_max_alloc,		0,		"set maximum size of a single allocated block", "bytes" },
    { "cpuflags",		 HAS_ARG | OPT_EXPERT,	NULL,				opt_cpuflags,		0,		"force specific cpu flags", "flags" },
    { "hide_banner",	 OPT_BOOL | OPT_EXPERT, &hide_banner,		NULL,				0,		"do not show program banner", "hide_banner" },
#if CONFIG_OPENCL
    { "opencl_bench",	 OPT_EXIT,				NULL,				opt_opencl_bench,	0,		"run benchmark on all OpenCL devices and show results", "" },
    { "opencl_options",  HAS_ARG,				NULL,				opt_opencl,			0,		"set OpenCL environment options", "" },
#endif
#if CONFIG_AVDEVICE
    { "sources",    	 OPT_EXIT | HAS_ARG,	NULL,				show_sources,		0,		"list sources of the input device", "device" },
    { "sinks",      	 OPT_EXIT | HAS_ARG,	NULL,				show_sinks,			0,      "list sinks of the output device", "device" },
#endif
